sudo: required
dist: trusty
git:
  depth: 1

language: node_js
node_js:
  - '6'
  - '7'
  - stable

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

matrix:
  fast_finish: true

env:
  global:
    secure: PimbLN6TbLkL9BLpmNgvdQQJO2NQKGm7y3iYCwgUT8AwTbeQ/lMV31pxDWDyOlut94SA4TtcvCJnTumY2Cc+TucacDTDgkSrHSaJraMCXqXbeh232jfcHij/SWmrX2hPiwjFl95FOt5csUUeBGzPLFpP42VuraBdxvc26tWBTs3O/sf5wIVRqCe3NxdUu1fZg4sZ/fYBCrKE9JhUoXWyAAM7pEdEZKkGuRmTAhoOpz8jTM9PX5wjsl838EDYDlDpCsgJnewFwZp+soryrzC2hTBUHyR6oeIfE1KgM0s0n0l4U4TgGj05QgVEc11rBI+sV4womhM9b5ycuH3XEmc5umflpcSk4nGERgF/wLoFEBZDwbK3Ly/eHlM54pqgH/a8Q+FY5KMS5Md97JVjzrJcRVDBB+Uk3PVN+Y/Ah7DtRLZR4zkmEHfZc6CeX832pfBzd2YXvqpMda/ttyd8uP6knS/SOS78UrcX5an8ABzkQJVdA0fRNuWLXRQDGpFqgzb31WwhVEPEeAPTYDQsiffAxruDcm3ncip663VKeA/iLn/UOqhiXtKqr1UdeUL5HgRlkJVw/+cqWSo+zrerIspfnpNzC0NfYiO6VLXuJccpKRPiwX1Q9dHnihI99rg4PSjADlxx7VQOuPyw6agrvvRIfZDqfF7jtKOctRGh+y0ROj8=

install:
  - npm install -g yo gulp bower
  - npm install
  - npm link

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test